# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types/algorithms.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'types/algorithms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from citius_api.types import templates_pb2 as types_dot_templates__pb2
from citius_api.buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16types/algorithms.proto\x12\x0e\x63\x61\x61s.crypto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15types/templates.proto\x1a\x1b\x62uf/validate/validate.proto\"\x94\x03\n\x18StandardAlgorithmCatalog\x12#\n\x07version\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x07version\x12=\n\x0clast_updated\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0blastUpdated\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12U\n\ttemplates\x18\x04 \x03(\x0b\x32\x37.caas.crypto.v1.StandardAlgorithmCatalog.TemplatesEntryR\ttemplates\x12?\n\x08\x66\x61milies\x18\x05 \x03(\x0b\x32#.caas.crypto.v1.AlgorithmFamilySpecR\x08\x66\x61milies\x1aZ\n\x0eTemplatesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32\x1c.caas.crypto.v1.TemplateInfoR\x05value:\x02\x38\x01\"\xe5\x02\n\x13\x41lgorithmFamilySpec\x12\"\n\x06\x66\x61mily\x18\x01 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x80\x01R\x06\x66\x61mily\x12!\n\x0c\x64isplay_name\x18\x02 \x01(\tR\x0b\x64isplayName\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12\x1c\n\tprimitive\x18\x04 \x01(\tR\tprimitive\x12\x1c\n\tstandards\x18\x05 \x03(\tR\tstandards\x12!\n\x0ctemplate_ids\x18\x06 \x03(\tR\x0btemplateIds\x12.\n\x13\x64\x65\x66\x61ult_template_id\x18\x07 \x01(\tR\x11\x64\x65\x66\x61ultTemplateId\x12(\n\x10has_pqc_variants\x18\x08 \x01(\x08R\x0ehasPqcVariants\x12,\n\x12min_security_level\x18\t \x01(\rR\x10minSecurityLevelB:Z8github.com/agile-crypto/citius-api-go/gen/go/types;typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'types.algorithms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/agile-crypto/citius-api-go/gen/go/types;types'
  _globals['_STANDARDALGORITHMCATALOG_TEMPLATESENTRY']._loaded_options = None
  _globals['_STANDARDALGORITHMCATALOG_TEMPLATESENTRY']._serialized_options = b'8\001'
  _globals['_STANDARDALGORITHMCATALOG'].fields_by_name['version']._loaded_options = None
  _globals['_STANDARDALGORITHMCATALOG'].fields_by_name['version']._serialized_options = b'\272H\006r\004\020\001\030@'
  _globals['_ALGORITHMFAMILYSPEC'].fields_by_name['family']._loaded_options = None
  _globals['_ALGORITHMFAMILYSPEC'].fields_by_name['family']._serialized_options = b'\272H\007r\005\020\001\030\200\001'
  _globals['_STANDARDALGORITHMCATALOG']._serialized_start=128
  _globals['_STANDARDALGORITHMCATALOG']._serialized_end=532
  _globals['_STANDARDALGORITHMCATALOG_TEMPLATESENTRY']._serialized_start=442
  _globals['_STANDARDALGORITHMCATALOG_TEMPLATESENTRY']._serialized_end=532
  _globals['_ALGORITHMFAMILYSPEC']._serialized_start=535
  _globals['_ALGORITHMFAMILYSPEC']._serialized_end=892
# @@protoc_insertion_point(module_scope)
