# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from citius_api.types import common_pb2 as types_dot_common__pb2
from citius_api.types import templates_pb2 as types_dot_templates__pb2
from citius_api.types import providers_pb2 as types_dot_providers__pb2
from citius_api.messages import metadata_pb2 as messages_dot_metadata__pb2
from citius_api.messages import key_management_pb2 as messages_dot_key__management__pb2
from citius_api.messages import encryption_pb2 as messages_dot_encryption__pb2
from citius_api.messages import signing_pb2 as messages_dot_signing__pb2
from citius_api.messages import digest_pb2 as messages_dot_digest__pb2
from citius_api.messages import key_derivation_pb2 as messages_dot_key__derivation__pb2
from citius_api.messages import key_encapsulation_pb2 as messages_dot_key__encapsulation__pb2
from citius_api.messages import key_wrapping_pb2 as messages_dot_key__wrapping__pb2
from citius_api.messages import mac_pb2 as messages_dot_mac__pb2
from citius_api.messages import random_pb2 as messages_dot_random__pb2
from citius_api.messages import policy_pb2 as messages_dot_policy__pb2
from citius_api.messages import session_pb2 as messages_dot_session__pb2
from citius_api.services import crypto_service_pb2 as services_dot_crypto__service__pb2
from citius_api.services import streaming_crypto_service_pb2 as services_dot_streaming__crypto__service__pb2
from citius_api.services import key_management_service_pb2 as services_dot_key__management__service__pb2
from citius_api.services import key_establishment_service_pb2 as services_dot_key__establishment__service__pb2
from citius_api.services import crypto_policy_service_pb2 as services_dot_crypto__policy__service__pb2
from citius_api.services import provider_service_pb2 as services_dot_provider__service__pb2
from citius_api.services import discovery_service_pb2 as services_dot_discovery__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x0e\x63\x61\x61s.crypto.v1\x1a\x12types/common.proto\x1a\x15types/templates.proto\x1a\x15types/providers.proto\x1a\x17messages/metadata.proto\x1a\x1dmessages/key_management.proto\x1a\x19messages/encryption.proto\x1a\x16messages/signing.proto\x1a\x15messages/digest.proto\x1a\x1dmessages/key_derivation.proto\x1a messages/key_encapsulation.proto\x1a\x1bmessages/key_wrapping.proto\x1a\x12messages/mac.proto\x1a\x15messages/random.proto\x1a\x15messages/policy.proto\x1a\x16messages/session.proto\x1a\x1dservices/crypto_service.proto\x1a\'services/streaming_crypto_service.proto\x1a%services/key_management_service.proto\x1a(services/key_establishment_service.proto\x1a$services/crypto_policy_service.proto\x1a\x1fservices/provider_service.proto\x1a services/discovery_service.protoB6Z4github.com/agile-crypto/citius-api-go/gen/go/api;apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/agile-crypto/citius-api-go/gen/go/api;api'
# @@protoc_insertion_point(module_scope)
