# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages/random.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'messages/random.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from citius_api.messages import metadata_pb2 as messages_dot_metadata__pb2
from citius_api.buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15messages/random.proto\x12\x0e\x63\x61\x61s.crypto.v1\x1a\x17messages/metadata.proto\x1a\x1b\x62uf/validate/validate.proto\"\x9e\x02\n\x15GenerateRandomRequest\x12(\n\tnum_bytes\x18\x01 \x01(\rB\x0b\xbaH\x08*\x06\x18\x80\x80@(\x01R\x08numBytes\x12\x1f\n\x0bprovider_id\x18\x02 \x01(\tR\nproviderId\x12\x1f\n\x0bpolicy_name\x18\x03 \x01(\tR\npolicyName\x12Y\n\x0cuser_context\x18\x0f \x03(\x0b\x32\x36.caas.crypto.v1.GenerateRandomRequest.UserContextEntryR\x0buserContext\x1a>\n\x10UserContextEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\x9b\x01\n\x16GenerateRandomResponse\x12!\n\x0crandom_bytes\x18\x01 \x01(\x0cR\x0brandomBytes\x12\x1f\n\x0bprovider_id\x18\x02 \x01(\tR\nproviderId\x12=\n\x08metadata\x18\x03 \x01(\x0b\x32!.caas.crypto.v1.OperationMetadataR\x08metadata\"\x80\x02\n\x11SeedRandomRequest\x12\x12\n\x04seed\x18\x01 \x01(\x0cR\x04seed\x12\x1f\n\x0bprovider_id\x18\x02 \x01(\tR\nproviderId\x12\x1f\n\x0bpolicy_name\x18\x03 \x01(\tR\npolicyName\x12U\n\x0cuser_context\x18\x0f \x03(\x0b\x32\x32.caas.crypto.v1.SeedRandomRequest.UserContextEntryR\x0buserContext\x1a>\n\x10UserContextEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"H\n\x12SeedRandomResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x18\n\x07message\x18\x02 \x01(\tR\x07messageB@Z>github.com/agile-crypto/citius-api-go/gen/go/messages;messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages.random_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/agile-crypto/citius-api-go/gen/go/messages;messages'
  _globals['_GENERATERANDOMREQUEST_USERCONTEXTENTRY']._loaded_options = None
  _globals['_GENERATERANDOMREQUEST_USERCONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_GENERATERANDOMREQUEST'].fields_by_name['num_bytes']._loaded_options = None
  _globals['_GENERATERANDOMREQUEST'].fields_by_name['num_bytes']._serialized_options = b'\272H\010*\006\030\200\200@(\001'
  _globals['_SEEDRANDOMREQUEST_USERCONTEXTENTRY']._loaded_options = None
  _globals['_SEEDRANDOMREQUEST_USERCONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_GENERATERANDOMREQUEST']._serialized_start=96
  _globals['_GENERATERANDOMREQUEST']._serialized_end=382
  _globals['_GENERATERANDOMREQUEST_USERCONTEXTENTRY']._serialized_start=320
  _globals['_GENERATERANDOMREQUEST_USERCONTEXTENTRY']._serialized_end=382
  _globals['_GENERATERANDOMRESPONSE']._serialized_start=385
  _globals['_GENERATERANDOMRESPONSE']._serialized_end=540
  _globals['_SEEDRANDOMREQUEST']._serialized_start=543
  _globals['_SEEDRANDOMREQUEST']._serialized_end=799
  _globals['_SEEDRANDOMREQUEST_USERCONTEXTENTRY']._serialized_start=320
  _globals['_SEEDRANDOMREQUEST_USERCONTEXTENTRY']._serialized_end=382
  _globals['_SEEDRANDOMRESPONSE']._serialized_start=801
  _globals['_SEEDRANDOMRESPONSE']._serialized_end=873
# @@protoc_insertion_point(module_scope)
