# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from citius_api.messages import digest_pb2 as messages_dot_digest__pb2
from citius_api.messages import encryption_pb2 as messages_dot_encryption__pb2
from citius_api.messages import mac_pb2 as messages_dot_mac__pb2
from citius_api.messages import random_pb2 as messages_dot_random__pb2
from citius_api.messages import signing_pb2 as messages_dot_signing__pb2


class CryptoServiceStub:
    """============================================================================
    Crypto Service - Single-Shot Cryptographic Operations
    ============================================================================

    All operations are stateless, single request/response

    This is part of the service family:
    - KeyManagementService:     Key lifecycle (CRUD, rotate, transform, migrate)
    - CryptoPolicyService:      Policy lifecycle and evaluation
    - CryptoService:            Single-shot crypto operations (this service)
    - StreamingCryptoService:   Multi-part and message-based stateful operations
    - KeyEstablishmentService:  Key-to-key operations (wrap, derive, KEM, agreement)
    - AlgorithmDiscoveryService: Template and scope discovery
    - ProviderService:          Provider catalog and instance management

    ==================== Encryption ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Encrypt = channel.unary_unary(
                '/caas.crypto.v1.CryptoService/Encrypt',
                request_serializer=messages_dot_encryption__pb2.EncryptRequest.SerializeToString,
                response_deserializer=messages_dot_encryption__pb2.EncryptResponse.FromString,
                _registered_method=True)
        self.Decrypt = channel.unary_unary(
                '/caas.crypto.v1.CryptoService/Decrypt',
                request_serializer=messages_dot_encryption__pb2.DecryptRequest.SerializeToString,
                response_deserializer=messages_dot_encryption__pb2.DecryptResponse.FromString,
                _registered_method=True)
        self.Sign = channel.unary_unary(
                '/caas.crypto.v1.CryptoService/Sign',
                request_serializer=messages_dot_signing__pb2.SignRequest.SerializeToString,
                response_deserializer=messages_dot_signing__pb2.SignResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/caas.crypto.v1.CryptoService/Verify',
                request_serializer=messages_dot_signing__pb2.VerifyRequest.SerializeToString,
                response_deserializer=messages_dot_signing__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.DigestSign = channel.unary_unary(
                '/caas.crypto.v1.CryptoService/DigestSign',
                request_serializer=messages_dot_signing__pb2.DigestSignRequest.SerializeToString,
                response_deserializer=messages_dot_signing__pb2.DigestSignResponse.FromString,
                _registered_method=True)
        self.DigestVerify = channel.unary_unary(
                '/caas.crypto.v1.CryptoService/DigestVerify',
                request_serializer=messages_dot_signing__pb2.DigestVerifyRequest.SerializeToString,
                response_deserializer=messages_dot_signing__pb2.DigestVerifyResponse.FromString,
                _registered_method=True)
        self.GenerateMAC = channel.unary_unary(
                '/caas.crypto.v1.CryptoService/GenerateMAC',
                request_serializer=messages_dot_mac__pb2.GenerateMACRequest.SerializeToString,
                response_deserializer=messages_dot_mac__pb2.GenerateMACResponse.FromString,
                _registered_method=True)
        self.VerifyMAC = channel.unary_unary(
                '/caas.crypto.v1.CryptoService/VerifyMAC',
                request_serializer=messages_dot_mac__pb2.VerifyMACRequest.SerializeToString,
                response_deserializer=messages_dot_mac__pb2.VerifyMACResponse.FromString,
                _registered_method=True)
        self.Digest = channel.unary_unary(
                '/caas.crypto.v1.CryptoService/Digest',
                request_serializer=messages_dot_digest__pb2.DigestRequest.SerializeToString,
                response_deserializer=messages_dot_digest__pb2.DigestResponse.FromString,
                _registered_method=True)
        self.Xof = channel.unary_unary(
                '/caas.crypto.v1.CryptoService/Xof',
                request_serializer=messages_dot_digest__pb2.XofRequest.SerializeToString,
                response_deserializer=messages_dot_digest__pb2.XofResponse.FromString,
                _registered_method=True)
        self.GenerateRandom = channel.unary_unary(
                '/caas.crypto.v1.CryptoService/GenerateRandom',
                request_serializer=messages_dot_random__pb2.GenerateRandomRequest.SerializeToString,
                response_deserializer=messages_dot_random__pb2.GenerateRandomResponse.FromString,
                _registered_method=True)
        self.SeedRandom = channel.unary_unary(
                '/caas.crypto.v1.CryptoService/SeedRandom',
                request_serializer=messages_dot_random__pb2.SeedRandomRequest.SerializeToString,
                response_deserializer=messages_dot_random__pb2.SeedRandomResponse.FromString,
                _registered_method=True)


class CryptoServiceServicer:
    """============================================================================
    Crypto Service - Single-Shot Cryptographic Operations
    ============================================================================

    All operations are stateless, single request/response

    This is part of the service family:
    - KeyManagementService:     Key lifecycle (CRUD, rotate, transform, migrate)
    - CryptoPolicyService:      Policy lifecycle and evaluation
    - CryptoService:            Single-shot crypto operations (this service)
    - StreamingCryptoService:   Multi-part and message-based stateful operations
    - KeyEstablishmentService:  Key-to-key operations (wrap, derive, KEM, agreement)
    - AlgorithmDiscoveryService: Template and scope discovery
    - ProviderService:          Provider catalog and instance management

    ==================== Encryption ====================
    """

    def Encrypt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decrypt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sign(self, request, context):
        """==================== Signing ====================

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DigestSign(self, request, context):
        """Sign/verify pre-hashed data (for large files, external hashing)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DigestVerify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateMAC(self, request, context):
        """==================== MAC Operations ====================

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyMAC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Digest(self, request, context):
        """==================== Digest Operations ====================

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Xof(self, request, context):
        """==================== XOF (Extendable Output Function) ====================
        XOFs produce variable-length output (SHAKE128, SHAKE256, BLAKE3, etc.)
        Separated from digest because they are a distinct primitive (CRYPTO_PRIMITIVE_XOF)
        with caller-specified output length.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateRandom(self, request, context):
        """==================== Random Number Generation ====================

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeedRandom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CryptoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Encrypt': grpc.unary_unary_rpc_method_handler(
                    servicer.Encrypt,
                    request_deserializer=messages_dot_encryption__pb2.EncryptRequest.FromString,
                    response_serializer=messages_dot_encryption__pb2.EncryptResponse.SerializeToString,
            ),
            'Decrypt': grpc.unary_unary_rpc_method_handler(
                    servicer.Decrypt,
                    request_deserializer=messages_dot_encryption__pb2.DecryptRequest.FromString,
                    response_serializer=messages_dot_encryption__pb2.DecryptResponse.SerializeToString,
            ),
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=messages_dot_signing__pb2.SignRequest.FromString,
                    response_serializer=messages_dot_signing__pb2.SignResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=messages_dot_signing__pb2.VerifyRequest.FromString,
                    response_serializer=messages_dot_signing__pb2.VerifyResponse.SerializeToString,
            ),
            'DigestSign': grpc.unary_unary_rpc_method_handler(
                    servicer.DigestSign,
                    request_deserializer=messages_dot_signing__pb2.DigestSignRequest.FromString,
                    response_serializer=messages_dot_signing__pb2.DigestSignResponse.SerializeToString,
            ),
            'DigestVerify': grpc.unary_unary_rpc_method_handler(
                    servicer.DigestVerify,
                    request_deserializer=messages_dot_signing__pb2.DigestVerifyRequest.FromString,
                    response_serializer=messages_dot_signing__pb2.DigestVerifyResponse.SerializeToString,
            ),
            'GenerateMAC': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateMAC,
                    request_deserializer=messages_dot_mac__pb2.GenerateMACRequest.FromString,
                    response_serializer=messages_dot_mac__pb2.GenerateMACResponse.SerializeToString,
            ),
            'VerifyMAC': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyMAC,
                    request_deserializer=messages_dot_mac__pb2.VerifyMACRequest.FromString,
                    response_serializer=messages_dot_mac__pb2.VerifyMACResponse.SerializeToString,
            ),
            'Digest': grpc.unary_unary_rpc_method_handler(
                    servicer.Digest,
                    request_deserializer=messages_dot_digest__pb2.DigestRequest.FromString,
                    response_serializer=messages_dot_digest__pb2.DigestResponse.SerializeToString,
            ),
            'Xof': grpc.unary_unary_rpc_method_handler(
                    servicer.Xof,
                    request_deserializer=messages_dot_digest__pb2.XofRequest.FromString,
                    response_serializer=messages_dot_digest__pb2.XofResponse.SerializeToString,
            ),
            'GenerateRandom': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateRandom,
                    request_deserializer=messages_dot_random__pb2.GenerateRandomRequest.FromString,
                    response_serializer=messages_dot_random__pb2.GenerateRandomResponse.SerializeToString,
            ),
            'SeedRandom': grpc.unary_unary_rpc_method_handler(
                    servicer.SeedRandom,
                    request_deserializer=messages_dot_random__pb2.SeedRandomRequest.FromString,
                    response_serializer=messages_dot_random__pb2.SeedRandomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'caas.crypto.v1.CryptoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('caas.crypto.v1.CryptoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CryptoService:
    """============================================================================
    Crypto Service - Single-Shot Cryptographic Operations
    ============================================================================

    All operations are stateless, single request/response

    This is part of the service family:
    - KeyManagementService:     Key lifecycle (CRUD, rotate, transform, migrate)
    - CryptoPolicyService:      Policy lifecycle and evaluation
    - CryptoService:            Single-shot crypto operations (this service)
    - StreamingCryptoService:   Multi-part and message-based stateful operations
    - KeyEstablishmentService:  Key-to-key operations (wrap, derive, KEM, agreement)
    - AlgorithmDiscoveryService: Template and scope discovery
    - ProviderService:          Provider catalog and instance management

    ==================== Encryption ====================
    """

    @staticmethod
    def Encrypt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.CryptoService/Encrypt',
            messages_dot_encryption__pb2.EncryptRequest.SerializeToString,
            messages_dot_encryption__pb2.EncryptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decrypt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.CryptoService/Decrypt',
            messages_dot_encryption__pb2.DecryptRequest.SerializeToString,
            messages_dot_encryption__pb2.DecryptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.CryptoService/Sign',
            messages_dot_signing__pb2.SignRequest.SerializeToString,
            messages_dot_signing__pb2.SignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.CryptoService/Verify',
            messages_dot_signing__pb2.VerifyRequest.SerializeToString,
            messages_dot_signing__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DigestSign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.CryptoService/DigestSign',
            messages_dot_signing__pb2.DigestSignRequest.SerializeToString,
            messages_dot_signing__pb2.DigestSignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DigestVerify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.CryptoService/DigestVerify',
            messages_dot_signing__pb2.DigestVerifyRequest.SerializeToString,
            messages_dot_signing__pb2.DigestVerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateMAC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.CryptoService/GenerateMAC',
            messages_dot_mac__pb2.GenerateMACRequest.SerializeToString,
            messages_dot_mac__pb2.GenerateMACResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyMAC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.CryptoService/VerifyMAC',
            messages_dot_mac__pb2.VerifyMACRequest.SerializeToString,
            messages_dot_mac__pb2.VerifyMACResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Digest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.CryptoService/Digest',
            messages_dot_digest__pb2.DigestRequest.SerializeToString,
            messages_dot_digest__pb2.DigestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Xof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.CryptoService/Xof',
            messages_dot_digest__pb2.XofRequest.SerializeToString,
            messages_dot_digest__pb2.XofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateRandom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.CryptoService/GenerateRandom',
            messages_dot_random__pb2.GenerateRandomRequest.SerializeToString,
            messages_dot_random__pb2.GenerateRandomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeedRandom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.CryptoService/SeedRandom',
            messages_dot_random__pb2.SeedRandomRequest.SerializeToString,
            messages_dot_random__pb2.SeedRandomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
