# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/crypto_policy_service.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'services/crypto_policy_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from citius_api.messages import policy_pb2 as messages_dot_policy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$services/crypto_policy_service.proto\x12\x0e\x63\x61\x61s.crypto.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x15messages/policy.proto2\xf0\x07\n\x13\x43ryptoPolicyService\x12\x8b\x01\n\x12\x43reateCryptoPolicy\x12).caas.crypto.v1.CreateCryptoPolicyRequest\x1a*.caas.crypto.v1.CreateCryptoPolicyResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x13/v1/policies/{name}:\x01*\x12\x82\x01\n\x10ReadCryptoPolicy\x12\'.caas.crypto.v1.ReadCryptoPolicyRequest\x1a(.caas.crypto.v1.ReadCryptoPolicyResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/policies/{name}\x12\x88\x01\n\x12\x44\x65leteCryptoPolicy\x12).caas.crypto.v1.DeleteCryptoPolicyRequest\x1a*.caas.crypto.v1.DeleteCryptoPolicyResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/policies/{name}\x12\x8b\x01\n\x12UpdateCryptoPolicy\x12).caas.crypto.v1.UpdateCryptoPolicyRequest\x1a*.caas.crypto.v1.UpdateCryptoPolicyResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x1a\x13/v1/policies/{name}:\x01*\x12\x81\x01\n\x12ListCryptoPolicies\x12).caas.crypto.v1.ListCryptoPoliciesRequest\x1a*.caas.crypto.v1.ListCryptoPoliciesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/v1/policies\x12\x8f\x01\n\x0e\x45valuatePolicy\x12%.caas.crypto.v1.EvaluatePolicyRequest\x1a&.caas.crypto.v1.EvaluatePolicyResponse\".\x82\xd3\xe4\x93\x02(\"#/v1/policies/{policy_name}/evaluate:\x01*\x12\x96\x01\n\x13\x42\x61tchEvaluatePolicy\x12*.caas.crypto.v1.BatchEvaluatePolicyRequest\x1a+.caas.crypto.v1.BatchEvaluatePolicyResponse\"&\x82\xd3\xe4\x93\x02 \"\x1b/v1/policies/evaluate/batch:\x01*B@Z>github.com/agile-crypto/citius-api-go/gen/go/services;servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.crypto_policy_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/agile-crypto/citius-api-go/gen/go/services;services'
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['CreateCryptoPolicy']._loaded_options = None
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['CreateCryptoPolicy']._serialized_options = b'\202\323\344\223\002\030\"\023/v1/policies/{name}:\001*'
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['ReadCryptoPolicy']._loaded_options = None
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['ReadCryptoPolicy']._serialized_options = b'\202\323\344\223\002\025\022\023/v1/policies/{name}'
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['DeleteCryptoPolicy']._loaded_options = None
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['DeleteCryptoPolicy']._serialized_options = b'\202\323\344\223\002\025*\023/v1/policies/{name}'
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['UpdateCryptoPolicy']._loaded_options = None
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['UpdateCryptoPolicy']._serialized_options = b'\202\323\344\223\002\030\032\023/v1/policies/{name}:\001*'
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['ListCryptoPolicies']._loaded_options = None
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['ListCryptoPolicies']._serialized_options = b'\202\323\344\223\002\016\022\014/v1/policies'
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['EvaluatePolicy']._loaded_options = None
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['EvaluatePolicy']._serialized_options = b'\202\323\344\223\002(\"#/v1/policies/{policy_name}/evaluate:\001*'
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['BatchEvaluatePolicy']._loaded_options = None
  _globals['_CRYPTOPOLICYSERVICE'].methods_by_name['BatchEvaluatePolicy']._serialized_options = b'\202\323\344\223\002 \"\033/v1/policies/evaluate/batch:\001*'
  _globals['_CRYPTOPOLICYSERVICE']._serialized_start=110
  _globals['_CRYPTOPOLICYSERVICE']._serialized_end=1118
# @@protoc_insertion_point(module_scope)
