# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from citius_api.services import discovery_service_pb2 as services_dot_discovery__service__pb2


class AlgorithmDiscoveryServiceStub:
    """============================================================================
    Algorithm Discovery Service
    ============================================================================

    SCOPE-BASED DISCOVERY MECHANISM:

    Templates are discovered via typed ScopeSpecification filtering. Clients specify
    the cryptographic primitive and its requirements; the service returns matching
    templates. Additional filters narrow results by lifecycle status and standards
    compliance.

    DISCOVERY PATTERNS:

    The API uses typed ScopeSpecification (per-primitive scope enums) for filtering,
    NOT a flat CRYPTO_SCOPE_* enum. See types/common.proto for ScopeSpecification.

    Pattern 1: Find AEAD templates with 256-bit security
    ListTemplatesRequest {
    scope_spec: {
    aead: { scope: AEAD_SCOPE_STANDARD, security: { security_strength_bits: 256 } }
    }
    }
    → Returns all AEAD templates with 256-bit keys

    Pattern 2: Find FIPS-approved signature templates
    ListTemplatesRequest {
    scope_spec: {
    signature: { scope: SIGNATURE_SCOPE_STANDARD, security: { fips_approved: true, security_strength_bits: 256 } }
    }
    allowed_statuses: [TEMPLATE_STATUS_ACTIVE]
    }
    → Returns only FIPS-approved, active signature templates with 256-bit strength

    Pattern 3: Find post-quantum signature options
    ListTemplatesRequest {
    scope_spec: {
    signature: { scope: SIGNATURE_SCOPE_STANDARD, security: { quantum_safe: true } }
    }
    }
    → Returns ML-DSA, SLH-DSA, and other post-quantum signature templates

    Pattern 4: Find templates compliant with specific standards
    ListTemplatesRequest {
    scope_spec: {
    kdf: { scope: KDF_SCOPE_PASSWORD }
    }
    required_standards: ["NIST SP 800-132"]
    }
    → Returns KDFs referencing NIST SP 800-132


    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTemplates = channel.unary_unary(
                '/caas.crypto.v1.AlgorithmDiscoveryService/ListTemplates',
                request_serializer=services_dot_discovery__service__pb2.ListTemplatesRequest.SerializeToString,
                response_deserializer=services_dot_discovery__service__pb2.ListTemplatesResponse.FromString,
                _registered_method=True)
        self.GetTemplate = channel.unary_unary(
                '/caas.crypto.v1.AlgorithmDiscoveryService/GetTemplate',
                request_serializer=services_dot_discovery__service__pb2.GetTemplateRequest.SerializeToString,
                response_deserializer=services_dot_discovery__service__pb2.GetTemplateResponse.FromString,
                _registered_method=True)
        self.ListScopes = channel.unary_unary(
                '/caas.crypto.v1.AlgorithmDiscoveryService/ListScopes',
                request_serializer=services_dot_discovery__service__pb2.ListScopesRequest.SerializeToString,
                response_deserializer=services_dot_discovery__service__pb2.ListScopesResponse.FromString,
                _registered_method=True)


class AlgorithmDiscoveryServiceServicer:
    """============================================================================
    Algorithm Discovery Service
    ============================================================================

    SCOPE-BASED DISCOVERY MECHANISM:

    Templates are discovered via typed ScopeSpecification filtering. Clients specify
    the cryptographic primitive and its requirements; the service returns matching
    templates. Additional filters narrow results by lifecycle status and standards
    compliance.

    DISCOVERY PATTERNS:

    The API uses typed ScopeSpecification (per-primitive scope enums) for filtering,
    NOT a flat CRYPTO_SCOPE_* enum. See types/common.proto for ScopeSpecification.

    Pattern 1: Find AEAD templates with 256-bit security
    ListTemplatesRequest {
    scope_spec: {
    aead: { scope: AEAD_SCOPE_STANDARD, security: { security_strength_bits: 256 } }
    }
    }
    → Returns all AEAD templates with 256-bit keys

    Pattern 2: Find FIPS-approved signature templates
    ListTemplatesRequest {
    scope_spec: {
    signature: { scope: SIGNATURE_SCOPE_STANDARD, security: { fips_approved: true, security_strength_bits: 256 } }
    }
    allowed_statuses: [TEMPLATE_STATUS_ACTIVE]
    }
    → Returns only FIPS-approved, active signature templates with 256-bit strength

    Pattern 3: Find post-quantum signature options
    ListTemplatesRequest {
    scope_spec: {
    signature: { scope: SIGNATURE_SCOPE_STANDARD, security: { quantum_safe: true } }
    }
    }
    → Returns ML-DSA, SLH-DSA, and other post-quantum signature templates

    Pattern 4: Find templates compliant with specific standards
    ListTemplatesRequest {
    scope_spec: {
    kdf: { scope: KDF_SCOPE_PASSWORD }
    }
    required_standards: ["NIST SP 800-132"]
    }
    → Returns KDFs referencing NIST SP 800-132


    """

    def ListTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScopes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlgorithmDiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTemplates,
                    request_deserializer=services_dot_discovery__service__pb2.ListTemplatesRequest.FromString,
                    response_serializer=services_dot_discovery__service__pb2.ListTemplatesResponse.SerializeToString,
            ),
            'GetTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTemplate,
                    request_deserializer=services_dot_discovery__service__pb2.GetTemplateRequest.FromString,
                    response_serializer=services_dot_discovery__service__pb2.GetTemplateResponse.SerializeToString,
            ),
            'ListScopes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScopes,
                    request_deserializer=services_dot_discovery__service__pb2.ListScopesRequest.FromString,
                    response_serializer=services_dot_discovery__service__pb2.ListScopesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'caas.crypto.v1.AlgorithmDiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('caas.crypto.v1.AlgorithmDiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlgorithmDiscoveryService:
    """============================================================================
    Algorithm Discovery Service
    ============================================================================

    SCOPE-BASED DISCOVERY MECHANISM:

    Templates are discovered via typed ScopeSpecification filtering. Clients specify
    the cryptographic primitive and its requirements; the service returns matching
    templates. Additional filters narrow results by lifecycle status and standards
    compliance.

    DISCOVERY PATTERNS:

    The API uses typed ScopeSpecification (per-primitive scope enums) for filtering,
    NOT a flat CRYPTO_SCOPE_* enum. See types/common.proto for ScopeSpecification.

    Pattern 1: Find AEAD templates with 256-bit security
    ListTemplatesRequest {
    scope_spec: {
    aead: { scope: AEAD_SCOPE_STANDARD, security: { security_strength_bits: 256 } }
    }
    }
    → Returns all AEAD templates with 256-bit keys

    Pattern 2: Find FIPS-approved signature templates
    ListTemplatesRequest {
    scope_spec: {
    signature: { scope: SIGNATURE_SCOPE_STANDARD, security: { fips_approved: true, security_strength_bits: 256 } }
    }
    allowed_statuses: [TEMPLATE_STATUS_ACTIVE]
    }
    → Returns only FIPS-approved, active signature templates with 256-bit strength

    Pattern 3: Find post-quantum signature options
    ListTemplatesRequest {
    scope_spec: {
    signature: { scope: SIGNATURE_SCOPE_STANDARD, security: { quantum_safe: true } }
    }
    }
    → Returns ML-DSA, SLH-DSA, and other post-quantum signature templates

    Pattern 4: Find templates compliant with specific standards
    ListTemplatesRequest {
    scope_spec: {
    kdf: { scope: KDF_SCOPE_PASSWORD }
    }
    required_standards: ["NIST SP 800-132"]
    }
    → Returns KDFs referencing NIST SP 800-132


    """

    @staticmethod
    def ListTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.AlgorithmDiscoveryService/ListTemplates',
            services_dot_discovery__service__pb2.ListTemplatesRequest.SerializeToString,
            services_dot_discovery__service__pb2.ListTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.AlgorithmDiscoveryService/GetTemplate',
            services_dot_discovery__service__pb2.GetTemplateRequest.SerializeToString,
            services_dot_discovery__service__pb2.GetTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScopes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.AlgorithmDiscoveryService/ListScopes',
            services_dot_discovery__service__pb2.ListScopesRequest.SerializeToString,
            services_dot_discovery__service__pb2.ListScopesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
