# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/discovery_service.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'services/discovery_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from citius_api.types import common_pb2 as types_dot_common__pb2
from citius_api.types import templates_pb2 as types_dot_templates__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n services/discovery_service.proto\x12\x0e\x63\x61\x61s.crypto.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x12types/common.proto\x1a\x15types/templates.proto\"\x8f\x02\n\x14ListTemplatesRequest\x12\x41\n\nscope_spec\x18\x01 \x01(\x0b\x32\".caas.crypto.v1.ScopeSpecificationR\tscopeSpec\x12I\n\x10\x61llowed_statuses\x18\x02 \x03(\x0e\x32\x1e.caas.crypto.v1.TemplateStatusR\x0f\x61llowedStatuses\x12-\n\x12required_standards\x18\x03 \x03(\tR\x11requiredStandards\x12\x1b\n\tpage_size\x18\n \x01(\x05R\x08pageSize\x12\x1d\n\npage_token\x18\x0b \x01(\tR\tpageToken\"{\n\x15ListTemplatesResponse\x12:\n\ttemplates\x18\x01 \x03(\x0b\x32\x1c.caas.crypto.v1.TemplateInfoR\ttemplates\x12&\n\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"5\n\x12GetTemplateRequest\x12\x1f\n\x0btemplate_id\x18\x01 \x01(\tR\ntemplateId\"O\n\x13GetTemplateResponse\x12\x38\n\x08template\x18\x01 \x01(\x0b\x32\x1c.caas.crypto.v1.TemplateInfoR\x08template\"\x13\n\x11ListScopesRequest\"G\n\x12ListScopesResponse\x12\x31\n\x06scopes\x18\x01 \x03(\x0b\x32\x19.caas.crypto.v1.ScopeInfoR\x06scopes2\xf6\x02\n\x19\x41lgorithmDiscoveryService\x12s\n\rListTemplates\x12$.caas.crypto.v1.ListTemplatesRequest\x1a%.caas.crypto.v1.ListTemplatesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/templates\x12{\n\x0bGetTemplate\x12\".caas.crypto.v1.GetTemplateRequest\x1a#.caas.crypto.v1.GetTemplateResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/templates/{template_id}\x12g\n\nListScopes\x12!.caas.crypto.v1.ListScopesRequest\x1a\".caas.crypto.v1.ListScopesResponse\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/v1/scopesB@Z>github.com/agile-crypto/citius-api-go/gen/go/services;servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.discovery_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/agile-crypto/citius-api-go/gen/go/services;services'
  _globals['_ALGORITHMDISCOVERYSERVICE'].methods_by_name['ListTemplates']._loaded_options = None
  _globals['_ALGORITHMDISCOVERYSERVICE'].methods_by_name['ListTemplates']._serialized_options = b'\202\323\344\223\002\017\022\r/v1/templates'
  _globals['_ALGORITHMDISCOVERYSERVICE'].methods_by_name['GetTemplate']._loaded_options = None
  _globals['_ALGORITHMDISCOVERYSERVICE'].methods_by_name['GetTemplate']._serialized_options = b'\202\323\344\223\002\035\022\033/v1/templates/{template_id}'
  _globals['_ALGORITHMDISCOVERYSERVICE'].methods_by_name['ListScopes']._loaded_options = None
  _globals['_ALGORITHMDISCOVERYSERVICE'].methods_by_name['ListScopes']._serialized_options = b'\202\323\344\223\002\014\022\n/v1/scopes'
  _globals['_LISTTEMPLATESREQUEST']._serialized_start=126
  _globals['_LISTTEMPLATESREQUEST']._serialized_end=397
  _globals['_LISTTEMPLATESRESPONSE']._serialized_start=399
  _globals['_LISTTEMPLATESRESPONSE']._serialized_end=522
  _globals['_GETTEMPLATEREQUEST']._serialized_start=524
  _globals['_GETTEMPLATEREQUEST']._serialized_end=577
  _globals['_GETTEMPLATERESPONSE']._serialized_start=579
  _globals['_GETTEMPLATERESPONSE']._serialized_end=658
  _globals['_LISTSCOPESREQUEST']._serialized_start=660
  _globals['_LISTSCOPESREQUEST']._serialized_end=679
  _globals['_LISTSCOPESRESPONSE']._serialized_start=681
  _globals['_LISTSCOPESRESPONSE']._serialized_end=752
  _globals['_ALGORITHMDISCOVERYSERVICE']._serialized_start=755
  _globals['_ALGORITHMDISCOVERYSERVICE']._serialized_end=1129
# @@protoc_insertion_point(module_scope)
