# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/key_establishment_service.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'services/key_establishment_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from citius_api.messages import key_wrapping_pb2 as messages_dot_key__wrapping__pb2
from citius_api.messages import key_derivation_pb2 as messages_dot_key__derivation__pb2
from citius_api.messages import key_encapsulation_pb2 as messages_dot_key__encapsulation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(services/key_establishment_service.proto\x12\x0e\x63\x61\x61s.crypto.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bmessages/key_wrapping.proto\x1a\x1dmessages/key_derivation.proto\x1a messages/key_encapsulation.proto2\xd3\x06\n\x17KeyEstablishmentService\x12x\n\x07WrapKey\x12\x1e.caas.crypto.v1.WrapKeyRequest\x1a\x1f.caas.crypto.v1.WrapKeyResponse\",\x82\xd3\xe4\x93\x02&\"!/v1/keys/{wrapping_key_name}/wrap:\x01*\x12\x80\x01\n\tUnwrapKey\x12 .caas.crypto.v1.UnwrapKeyRequest\x1a!.caas.crypto.v1.UnwrapKeyResponse\".\x82\xd3\xe4\x93\x02(\"#/v1/keys/{wrapping_key_name}/unwrap:\x01*\x12|\n\tDeriveKey\x12 .caas.crypto.v1.DeriveKeyRequest\x1a!.caas.crypto.v1.DeriveKeyResponse\"*\x82\xd3\xe4\x93\x02$\"\x1f/v1/keys/{base_key_name}/derive:\x01*\x12\x87\x01\n\x0cKeyAgreement\x12#.caas.crypto.v1.KeyAgreementRequest\x1a$.caas.crypto.v1.KeyAgreementResponse\",\x82\xd3\xe4\x93\x02&\"!/v1/keys/{private_key_name}/agree:\x01*\x12\x9c\x01\n\x0e\x45ncapsulateKey\x12%.caas.crypto.v1.EncapsulateKeyRequest\x1a&.caas.crypto.v1.EncapsulateKeyResponse\";\x82\xd3\xe4\x93\x02\x35\"0/v1/keys/{recipient_public_key_name}/encapsulate:\x01*\x12\x93\x01\n\x0e\x44\x65\x63\x61psulateKey\x12%.caas.crypto.v1.DecapsulateKeyRequest\x1a&.caas.crypto.v1.DecapsulateKeyResponse\"2\x82\xd3\xe4\x93\x02,\"\'/v1/keys/{private_key_name}/decapsulate:\x01*B@Z>github.com/agile-crypto/citius-api-go/gen/go/services;servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.key_establishment_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/agile-crypto/citius-api-go/gen/go/services;services'
  _globals['_KEYESTABLISHMENTSERVICE'].methods_by_name['WrapKey']._loaded_options = None
  _globals['_KEYESTABLISHMENTSERVICE'].methods_by_name['WrapKey']._serialized_options = b'\202\323\344\223\002&\"!/v1/keys/{wrapping_key_name}/wrap:\001*'
  _globals['_KEYESTABLISHMENTSERVICE'].methods_by_name['UnwrapKey']._loaded_options = None
  _globals['_KEYESTABLISHMENTSERVICE'].methods_by_name['UnwrapKey']._serialized_options = b'\202\323\344\223\002(\"#/v1/keys/{wrapping_key_name}/unwrap:\001*'
  _globals['_KEYESTABLISHMENTSERVICE'].methods_by_name['DeriveKey']._loaded_options = None
  _globals['_KEYESTABLISHMENTSERVICE'].methods_by_name['DeriveKey']._serialized_options = b'\202\323\344\223\002$\"\037/v1/keys/{base_key_name}/derive:\001*'
  _globals['_KEYESTABLISHMENTSERVICE'].methods_by_name['KeyAgreement']._loaded_options = None
  _globals['_KEYESTABLISHMENTSERVICE'].methods_by_name['KeyAgreement']._serialized_options = b'\202\323\344\223\002&\"!/v1/keys/{private_key_name}/agree:\001*'
  _globals['_KEYESTABLISHMENTSERVICE'].methods_by_name['EncapsulateKey']._loaded_options = None
  _globals['_KEYESTABLISHMENTSERVICE'].methods_by_name['EncapsulateKey']._serialized_options = b'\202\323\344\223\0025\"0/v1/keys/{recipient_public_key_name}/encapsulate:\001*'
  _globals['_KEYESTABLISHMENTSERVICE'].methods_by_name['DecapsulateKey']._loaded_options = None
  _globals['_KEYESTABLISHMENTSERVICE'].methods_by_name['DecapsulateKey']._serialized_options = b'\202\323\344\223\002,\"\'/v1/keys/{private_key_name}/decapsulate:\001*'
  _globals['_KEYESTABLISHMENTSERVICE']._serialized_start=185
  _globals['_KEYESTABLISHMENTSERVICE']._serialized_end=1036
# @@protoc_insertion_point(module_scope)
