# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from citius_api.messages import key_management_pb2 as messages_dot_key__management__pb2


class KeyManagementServiceStub:
    """============================================================================
    Key Management Service - Key Lifecycle Operations
    ============================================================================

    This service manages the lifecycle of cryptographic keys:
    - CRUD operations (create, read, list, delete)
    - Lifecycle operations (rotate, transform, migrate)
    - Import/export for interoperability
    - Policy binding (UpdateKeyPolicy)
    - Pre-flight validation (ValidateKeyOperation)

    Resource: Keys (/v1/keys/*)
    Persona:  Key administrators
    IAM scope: keys.create, keys.read, keys.delete, keys.rotate,
    keys.transform, keys.migrate, keys.export, keys.import

    All key creation supports two selection modes:
    - Scope-based (policy determines template) — recommended
    - Explicit template_id (discovered via AlgorithmDiscoveryService)


    ==================== Key CRUD ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateKey = channel.unary_unary(
                '/caas.crypto.v1.KeyManagementService/CreateKey',
                request_serializer=messages_dot_key__management__pb2.CreateKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__management__pb2.CreateKeyResponse.FromString,
                _registered_method=True)
        self.ReadKey = channel.unary_unary(
                '/caas.crypto.v1.KeyManagementService/ReadKey',
                request_serializer=messages_dot_key__management__pb2.ReadKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__management__pb2.ReadKeyResponse.FromString,
                _registered_method=True)
        self.ListKeys = channel.unary_unary(
                '/caas.crypto.v1.KeyManagementService/ListKeys',
                request_serializer=messages_dot_key__management__pb2.ListKeysRequest.SerializeToString,
                response_deserializer=messages_dot_key__management__pb2.ListKeysResponse.FromString,
                _registered_method=True)
        self.DeleteKey = channel.unary_unary(
                '/caas.crypto.v1.KeyManagementService/DeleteKey',
                request_serializer=messages_dot_key__management__pb2.DeleteKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__management__pb2.DeleteKeyResponse.FromString,
                _registered_method=True)
        self.RotateKey = channel.unary_unary(
                '/caas.crypto.v1.KeyManagementService/RotateKey',
                request_serializer=messages_dot_key__management__pb2.RotateKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__management__pb2.RotateKeyResponse.FromString,
                _registered_method=True)
        self.TransformKey = channel.unary_unary(
                '/caas.crypto.v1.KeyManagementService/TransformKey',
                request_serializer=messages_dot_key__management__pb2.TransformKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__management__pb2.TransformKeyResponse.FromString,
                _registered_method=True)
        self.UpdateKeyState = channel.unary_unary(
                '/caas.crypto.v1.KeyManagementService/UpdateKeyState',
                request_serializer=messages_dot_key__management__pb2.UpdateKeyStateRequest.SerializeToString,
                response_deserializer=messages_dot_key__management__pb2.UpdateKeyStateResponse.FromString,
                _registered_method=True)
        self.UpdateKeyPolicy = channel.unary_unary(
                '/caas.crypto.v1.KeyManagementService/UpdateKeyPolicy',
                request_serializer=messages_dot_key__management__pb2.UpdateKeyPolicyRequest.SerializeToString,
                response_deserializer=messages_dot_key__management__pb2.UpdateKeyPolicyResponse.FromString,
                _registered_method=True)
        self.MigrateKey = channel.unary_unary(
                '/caas.crypto.v1.KeyManagementService/MigrateKey',
                request_serializer=messages_dot_key__management__pb2.MigrateKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__management__pb2.MigrateKeyResponse.FromString,
                _registered_method=True)
        self.ValidateKeyOperation = channel.unary_unary(
                '/caas.crypto.v1.KeyManagementService/ValidateKeyOperation',
                request_serializer=messages_dot_key__management__pb2.ValidateKeyOperationRequest.SerializeToString,
                response_deserializer=messages_dot_key__management__pb2.ValidateKeyOperationResponse.FromString,
                _registered_method=True)
        self.ExportKey = channel.unary_unary(
                '/caas.crypto.v1.KeyManagementService/ExportKey',
                request_serializer=messages_dot_key__management__pb2.ExportKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__management__pb2.ExportKeyResponse.FromString,
                _registered_method=True)
        self.ImportKey = channel.unary_unary(
                '/caas.crypto.v1.KeyManagementService/ImportKey',
                request_serializer=messages_dot_key__management__pb2.ImportKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__management__pb2.ImportKeyResponse.FromString,
                _registered_method=True)


class KeyManagementServiceServicer:
    """============================================================================
    Key Management Service - Key Lifecycle Operations
    ============================================================================

    This service manages the lifecycle of cryptographic keys:
    - CRUD operations (create, read, list, delete)
    - Lifecycle operations (rotate, transform, migrate)
    - Import/export for interoperability
    - Policy binding (UpdateKeyPolicy)
    - Pre-flight validation (ValidateKeyOperation)

    Resource: Keys (/v1/keys/*)
    Persona:  Key administrators
    IAM scope: keys.create, keys.read, keys.delete, keys.rotate,
    keys.transform, keys.migrate, keys.export, keys.import

    All key creation supports two selection modes:
    - Scope-based (policy determines template) — recommended
    - Explicit template_id (discovered via AlgorithmDiscoveryService)


    ==================== Key CRUD ====================
    """

    def CreateKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateKey(self, request, context):
        """==================== Key Lifecycle ====================

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransformKey(self, request, context):
        """TransformKey changes a key's algorithm while preserving its identity.
        The key enabler for cryptographic agility.
        retain_key_bytes=true:  Same material, different operation properties
        retain_key_bytes=false: Regenerate material (required for algorithm family change)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateKeyState(self, request, context):
        """UpdateKeyState performs an explicit, auditable lifecycle state transition
        (activate, suspend, reactivate, deactivate, mark compromised) per
        NIST SP 800-57 Part 1 §7. Destruction goes through DeleteKey.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateKeyPolicy(self, request, context):
        """UpdateKeyPolicy modifies the crypto policy binding for a key.
        This is a sub-resource operation on the key, not on the policy resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MigrateKey(self, request, context):
        """MigrateKey - Move key to different provider with explicit strategy

        Moves a key to a different provider with explicit migration strategy.
        User must specify how key material is handled during migration.

        Strategies:
        PROVIDER_SWITCH: SW→SW metadata-only change
        EXTRACT_AND_IMPORT: Key crosses security boundary
        WRAPPED_TRANSFER: HSM→HSM with maximum security
        REKEY_AND_ARCHIVE: New key, archive old (always works)
        REKEY_AND_DESTROY: New key, destroy old (careful!)

        See docs/TRANSFORM_KEY_PROVIDER_DESIGN.md for decision tree.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateKeyOperation(self, request, context):
        """ValidateKeyOperation - Pre-flight check for key operations

        Returns which strategies are feasible for a given key and target.
        Use before MigrateKey to show users available options.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportKey(self, request, context):
        """==================== Key Import/Export ====================

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateKey,
                    request_deserializer=messages_dot_key__management__pb2.CreateKeyRequest.FromString,
                    response_serializer=messages_dot_key__management__pb2.CreateKeyResponse.SerializeToString,
            ),
            'ReadKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadKey,
                    request_deserializer=messages_dot_key__management__pb2.ReadKeyRequest.FromString,
                    response_serializer=messages_dot_key__management__pb2.ReadKeyResponse.SerializeToString,
            ),
            'ListKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKeys,
                    request_deserializer=messages_dot_key__management__pb2.ListKeysRequest.FromString,
                    response_serializer=messages_dot_key__management__pb2.ListKeysResponse.SerializeToString,
            ),
            'DeleteKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKey,
                    request_deserializer=messages_dot_key__management__pb2.DeleteKeyRequest.FromString,
                    response_serializer=messages_dot_key__management__pb2.DeleteKeyResponse.SerializeToString,
            ),
            'RotateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateKey,
                    request_deserializer=messages_dot_key__management__pb2.RotateKeyRequest.FromString,
                    response_serializer=messages_dot_key__management__pb2.RotateKeyResponse.SerializeToString,
            ),
            'TransformKey': grpc.unary_unary_rpc_method_handler(
                    servicer.TransformKey,
                    request_deserializer=messages_dot_key__management__pb2.TransformKeyRequest.FromString,
                    response_serializer=messages_dot_key__management__pb2.TransformKeyResponse.SerializeToString,
            ),
            'UpdateKeyState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKeyState,
                    request_deserializer=messages_dot_key__management__pb2.UpdateKeyStateRequest.FromString,
                    response_serializer=messages_dot_key__management__pb2.UpdateKeyStateResponse.SerializeToString,
            ),
            'UpdateKeyPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKeyPolicy,
                    request_deserializer=messages_dot_key__management__pb2.UpdateKeyPolicyRequest.FromString,
                    response_serializer=messages_dot_key__management__pb2.UpdateKeyPolicyResponse.SerializeToString,
            ),
            'MigrateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.MigrateKey,
                    request_deserializer=messages_dot_key__management__pb2.MigrateKeyRequest.FromString,
                    response_serializer=messages_dot_key__management__pb2.MigrateKeyResponse.SerializeToString,
            ),
            'ValidateKeyOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateKeyOperation,
                    request_deserializer=messages_dot_key__management__pb2.ValidateKeyOperationRequest.FromString,
                    response_serializer=messages_dot_key__management__pb2.ValidateKeyOperationResponse.SerializeToString,
            ),
            'ExportKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportKey,
                    request_deserializer=messages_dot_key__management__pb2.ExportKeyRequest.FromString,
                    response_serializer=messages_dot_key__management__pb2.ExportKeyResponse.SerializeToString,
            ),
            'ImportKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportKey,
                    request_deserializer=messages_dot_key__management__pb2.ImportKeyRequest.FromString,
                    response_serializer=messages_dot_key__management__pb2.ImportKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'caas.crypto.v1.KeyManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('caas.crypto.v1.KeyManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyManagementService:
    """============================================================================
    Key Management Service - Key Lifecycle Operations
    ============================================================================

    This service manages the lifecycle of cryptographic keys:
    - CRUD operations (create, read, list, delete)
    - Lifecycle operations (rotate, transform, migrate)
    - Import/export for interoperability
    - Policy binding (UpdateKeyPolicy)
    - Pre-flight validation (ValidateKeyOperation)

    Resource: Keys (/v1/keys/*)
    Persona:  Key administrators
    IAM scope: keys.create, keys.read, keys.delete, keys.rotate,
    keys.transform, keys.migrate, keys.export, keys.import

    All key creation supports two selection modes:
    - Scope-based (policy determines template) — recommended
    - Explicit template_id (discovered via AlgorithmDiscoveryService)


    ==================== Key CRUD ====================
    """

    @staticmethod
    def CreateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyManagementService/CreateKey',
            messages_dot_key__management__pb2.CreateKeyRequest.SerializeToString,
            messages_dot_key__management__pb2.CreateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyManagementService/ReadKey',
            messages_dot_key__management__pb2.ReadKeyRequest.SerializeToString,
            messages_dot_key__management__pb2.ReadKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyManagementService/ListKeys',
            messages_dot_key__management__pb2.ListKeysRequest.SerializeToString,
            messages_dot_key__management__pb2.ListKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyManagementService/DeleteKey',
            messages_dot_key__management__pb2.DeleteKeyRequest.SerializeToString,
            messages_dot_key__management__pb2.DeleteKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyManagementService/RotateKey',
            messages_dot_key__management__pb2.RotateKeyRequest.SerializeToString,
            messages_dot_key__management__pb2.RotateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransformKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyManagementService/TransformKey',
            messages_dot_key__management__pb2.TransformKeyRequest.SerializeToString,
            messages_dot_key__management__pb2.TransformKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateKeyState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyManagementService/UpdateKeyState',
            messages_dot_key__management__pb2.UpdateKeyStateRequest.SerializeToString,
            messages_dot_key__management__pb2.UpdateKeyStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateKeyPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyManagementService/UpdateKeyPolicy',
            messages_dot_key__management__pb2.UpdateKeyPolicyRequest.SerializeToString,
            messages_dot_key__management__pb2.UpdateKeyPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MigrateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyManagementService/MigrateKey',
            messages_dot_key__management__pb2.MigrateKeyRequest.SerializeToString,
            messages_dot_key__management__pb2.MigrateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateKeyOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyManagementService/ValidateKeyOperation',
            messages_dot_key__management__pb2.ValidateKeyOperationRequest.SerializeToString,
            messages_dot_key__management__pb2.ValidateKeyOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyManagementService/ExportKey',
            messages_dot_key__management__pb2.ExportKeyRequest.SerializeToString,
            messages_dot_key__management__pb2.ExportKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyManagementService/ImportKey',
            messages_dot_key__management__pb2.ImportKeyRequest.SerializeToString,
            messages_dot_key__management__pb2.ImportKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
