# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from citius_api.messages import key_derivation_pb2 as messages_dot_key__derivation__pb2
from citius_api.messages import key_encapsulation_pb2 as messages_dot_key__encapsulation__pb2
from citius_api.messages import key_wrapping_pb2 as messages_dot_key__wrapping__pb2


class KeyEstablishmentServiceStub:
    """============================================================================
    Key Establishment Service - Key-to-Key Cryptographic Operations
    ============================================================================

    This service provides operations where keys act on keys — the output of
    every RPC is a new key stored in the key store.

    Covers all four NIST key establishment categories:
    - Key Transport (SP 800-56B):     WrapKey / UnwrapKey
    - Key Agreement (SP 800-56A):     KeyAgreement (ECDH, X25519, X448)
    - Key Encapsulation (SP 800-56C): EncapsulateKey / DecapsulateKey (ML-KEM)
    - Key Derivation (SP 800-56C 4, SP 800-108): DeriveKey (HKDF, PBKDF2)

    Naming rationale: NIST SP 800-56A/B defines "key establishment" as:
    "The process by which keying material is made available to two or more
    parties, with the guarantee that no unauthorized party can gain access
    to the keying material."
    SP 800-56C explicitly links key derivation as the final step that extracts
    usable keying material from a shared secret.

    ==================== Key Wrapping / Transport ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WrapKey = channel.unary_unary(
                '/caas.crypto.v1.KeyEstablishmentService/WrapKey',
                request_serializer=messages_dot_key__wrapping__pb2.WrapKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__wrapping__pb2.WrapKeyResponse.FromString,
                _registered_method=True)
        self.UnwrapKey = channel.unary_unary(
                '/caas.crypto.v1.KeyEstablishmentService/UnwrapKey',
                request_serializer=messages_dot_key__wrapping__pb2.UnwrapKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__wrapping__pb2.UnwrapKeyResponse.FromString,
                _registered_method=True)
        self.DeriveKey = channel.unary_unary(
                '/caas.crypto.v1.KeyEstablishmentService/DeriveKey',
                request_serializer=messages_dot_key__derivation__pb2.DeriveKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__derivation__pb2.DeriveKeyResponse.FromString,
                _registered_method=True)
        self.KeyAgreement = channel.unary_unary(
                '/caas.crypto.v1.KeyEstablishmentService/KeyAgreement',
                request_serializer=messages_dot_key__derivation__pb2.KeyAgreementRequest.SerializeToString,
                response_deserializer=messages_dot_key__derivation__pb2.KeyAgreementResponse.FromString,
                _registered_method=True)
        self.EncapsulateKey = channel.unary_unary(
                '/caas.crypto.v1.KeyEstablishmentService/EncapsulateKey',
                request_serializer=messages_dot_key__encapsulation__pb2.EncapsulateKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__encapsulation__pb2.EncapsulateKeyResponse.FromString,
                _registered_method=True)
        self.DecapsulateKey = channel.unary_unary(
                '/caas.crypto.v1.KeyEstablishmentService/DecapsulateKey',
                request_serializer=messages_dot_key__encapsulation__pb2.DecapsulateKeyRequest.SerializeToString,
                response_deserializer=messages_dot_key__encapsulation__pb2.DecapsulateKeyResponse.FromString,
                _registered_method=True)


class KeyEstablishmentServiceServicer:
    """============================================================================
    Key Establishment Service - Key-to-Key Cryptographic Operations
    ============================================================================

    This service provides operations where keys act on keys — the output of
    every RPC is a new key stored in the key store.

    Covers all four NIST key establishment categories:
    - Key Transport (SP 800-56B):     WrapKey / UnwrapKey
    - Key Agreement (SP 800-56A):     KeyAgreement (ECDH, X25519, X448)
    - Key Encapsulation (SP 800-56C): EncapsulateKey / DecapsulateKey (ML-KEM)
    - Key Derivation (SP 800-56C 4, SP 800-108): DeriveKey (HKDF, PBKDF2)

    Naming rationale: NIST SP 800-56A/B defines "key establishment" as:
    "The process by which keying material is made available to two or more
    parties, with the guarantee that no unauthorized party can gain access
    to the keying material."
    SP 800-56C explicitly links key derivation as the final step that extracts
    usable keying material from a shared secret.

    ==================== Key Wrapping / Transport ====================
    """

    def WrapKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnwrapKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeriveKey(self, request, context):
        """==================== Key Derivation ====================

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KeyAgreement(self, request, context):
        """KeyAgreement performs a two-party key agreement (ECDH/X25519/X448/X3DH)
        and stores the resulting shared secret as a named key.
        Distinct from DeriveKey: both parties contribute a key to produce a
        shared secret. No explicit KDF stage is required — the agreement
        protocol itself produces the output (though some protocols like
        X9.42 DH include an integrated KDF step).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncapsulateKey(self, request, context):
        """==================== Key Encapsulation (Post-Quantum KEMs) ====================

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecapsulateKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyEstablishmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WrapKey': grpc.unary_unary_rpc_method_handler(
                    servicer.WrapKey,
                    request_deserializer=messages_dot_key__wrapping__pb2.WrapKeyRequest.FromString,
                    response_serializer=messages_dot_key__wrapping__pb2.WrapKeyResponse.SerializeToString,
            ),
            'UnwrapKey': grpc.unary_unary_rpc_method_handler(
                    servicer.UnwrapKey,
                    request_deserializer=messages_dot_key__wrapping__pb2.UnwrapKeyRequest.FromString,
                    response_serializer=messages_dot_key__wrapping__pb2.UnwrapKeyResponse.SerializeToString,
            ),
            'DeriveKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeriveKey,
                    request_deserializer=messages_dot_key__derivation__pb2.DeriveKeyRequest.FromString,
                    response_serializer=messages_dot_key__derivation__pb2.DeriveKeyResponse.SerializeToString,
            ),
            'KeyAgreement': grpc.unary_unary_rpc_method_handler(
                    servicer.KeyAgreement,
                    request_deserializer=messages_dot_key__derivation__pb2.KeyAgreementRequest.FromString,
                    response_serializer=messages_dot_key__derivation__pb2.KeyAgreementResponse.SerializeToString,
            ),
            'EncapsulateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.EncapsulateKey,
                    request_deserializer=messages_dot_key__encapsulation__pb2.EncapsulateKeyRequest.FromString,
                    response_serializer=messages_dot_key__encapsulation__pb2.EncapsulateKeyResponse.SerializeToString,
            ),
            'DecapsulateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DecapsulateKey,
                    request_deserializer=messages_dot_key__encapsulation__pb2.DecapsulateKeyRequest.FromString,
                    response_serializer=messages_dot_key__encapsulation__pb2.DecapsulateKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'caas.crypto.v1.KeyEstablishmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('caas.crypto.v1.KeyEstablishmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyEstablishmentService:
    """============================================================================
    Key Establishment Service - Key-to-Key Cryptographic Operations
    ============================================================================

    This service provides operations where keys act on keys — the output of
    every RPC is a new key stored in the key store.

    Covers all four NIST key establishment categories:
    - Key Transport (SP 800-56B):     WrapKey / UnwrapKey
    - Key Agreement (SP 800-56A):     KeyAgreement (ECDH, X25519, X448)
    - Key Encapsulation (SP 800-56C): EncapsulateKey / DecapsulateKey (ML-KEM)
    - Key Derivation (SP 800-56C 4, SP 800-108): DeriveKey (HKDF, PBKDF2)

    Naming rationale: NIST SP 800-56A/B defines "key establishment" as:
    "The process by which keying material is made available to two or more
    parties, with the guarantee that no unauthorized party can gain access
    to the keying material."
    SP 800-56C explicitly links key derivation as the final step that extracts
    usable keying material from a shared secret.

    ==================== Key Wrapping / Transport ====================
    """

    @staticmethod
    def WrapKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyEstablishmentService/WrapKey',
            messages_dot_key__wrapping__pb2.WrapKeyRequest.SerializeToString,
            messages_dot_key__wrapping__pb2.WrapKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnwrapKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyEstablishmentService/UnwrapKey',
            messages_dot_key__wrapping__pb2.UnwrapKeyRequest.SerializeToString,
            messages_dot_key__wrapping__pb2.UnwrapKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeriveKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyEstablishmentService/DeriveKey',
            messages_dot_key__derivation__pb2.DeriveKeyRequest.SerializeToString,
            messages_dot_key__derivation__pb2.DeriveKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KeyAgreement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyEstablishmentService/KeyAgreement',
            messages_dot_key__derivation__pb2.KeyAgreementRequest.SerializeToString,
            messages_dot_key__derivation__pb2.KeyAgreementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncapsulateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyEstablishmentService/EncapsulateKey',
            messages_dot_key__encapsulation__pb2.EncapsulateKeyRequest.SerializeToString,
            messages_dot_key__encapsulation__pb2.EncapsulateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecapsulateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.KeyEstablishmentService/DecapsulateKey',
            messages_dot_key__encapsulation__pb2.DecapsulateKeyRequest.SerializeToString,
            messages_dot_key__encapsulation__pb2.DecapsulateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
