# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from citius_api.services import provider_service_pb2 as services_dot_provider__service__pb2


class ProviderServiceStub:
    """============================================================================
    Provider Service - Provider Discovery and Instance Management
    ============================================================================

    This service provides two main capabilities:

    1. Provider Capabilities (static catalog):
    - ListProviders / GetProvider: Query the provider type catalog
    - ProviderInfo describes what each provider TYPE can do (algorithms, properties)
    - Data comes from JSON files shipped with the service

    2. Provider Instances (runtime configuration):
    - RegisterProviderInstance / UpdateProviderInstance / DeleteProviderInstance
    - ProviderInstance represents a CONFIGURED, READY-TO-USE provider
    - Multiple instances can exist per provider type (e.g., different HSM slots)
    - Instances are stored in Vault/storage, not in files

    Example workflow:
    1. Admin queries ListProviders to see available provider types
    2. Admin registers instance: { provider_id: "pkcs11", instance_id: "hsm-payments", config: {...} }
    3. User creates key: { provider_requirements: { fips_140_certified: true } }
    4. System matches requirements to instances, selects "hsm-payments"


    ========================================
    Provider Capabilities (static catalog)
    ========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProviders = channel.unary_unary(
                '/caas.crypto.v1.ProviderService/ListProviders',
                request_serializer=services_dot_provider__service__pb2.ListProvidersRequest.SerializeToString,
                response_deserializer=services_dot_provider__service__pb2.ListProvidersResponse.FromString,
                _registered_method=True)
        self.GetProvider = channel.unary_unary(
                '/caas.crypto.v1.ProviderService/GetProvider',
                request_serializer=services_dot_provider__service__pb2.GetProviderRequest.SerializeToString,
                response_deserializer=services_dot_provider__service__pb2.GetProviderResponse.FromString,
                _registered_method=True)
        self.RegisterProviderInstance = channel.unary_unary(
                '/caas.crypto.v1.ProviderService/RegisterProviderInstance',
                request_serializer=services_dot_provider__service__pb2.RegisterProviderInstanceRequest.SerializeToString,
                response_deserializer=services_dot_provider__service__pb2.RegisterProviderInstanceResponse.FromString,
                _registered_method=True)
        self.ListProviderInstances = channel.unary_unary(
                '/caas.crypto.v1.ProviderService/ListProviderInstances',
                request_serializer=services_dot_provider__service__pb2.ListProviderInstancesRequest.SerializeToString,
                response_deserializer=services_dot_provider__service__pb2.ListProviderInstancesResponse.FromString,
                _registered_method=True)
        self.GetProviderInstance = channel.unary_unary(
                '/caas.crypto.v1.ProviderService/GetProviderInstance',
                request_serializer=services_dot_provider__service__pb2.GetProviderInstanceRequest.SerializeToString,
                response_deserializer=services_dot_provider__service__pb2.GetProviderInstanceResponse.FromString,
                _registered_method=True)
        self.UpdateProviderInstance = channel.unary_unary(
                '/caas.crypto.v1.ProviderService/UpdateProviderInstance',
                request_serializer=services_dot_provider__service__pb2.UpdateProviderInstanceRequest.SerializeToString,
                response_deserializer=services_dot_provider__service__pb2.UpdateProviderInstanceResponse.FromString,
                _registered_method=True)
        self.DeleteProviderInstance = channel.unary_unary(
                '/caas.crypto.v1.ProviderService/DeleteProviderInstance',
                request_serializer=services_dot_provider__service__pb2.DeleteProviderInstanceRequest.SerializeToString,
                response_deserializer=services_dot_provider__service__pb2.DeleteProviderInstanceResponse.FromString,
                _registered_method=True)
        self.MatchProviders = channel.unary_unary(
                '/caas.crypto.v1.ProviderService/MatchProviders',
                request_serializer=services_dot_provider__service__pb2.MatchProvidersRequest.SerializeToString,
                response_deserializer=services_dot_provider__service__pb2.MatchProvidersResponse.FromString,
                _registered_method=True)


class ProviderServiceServicer:
    """============================================================================
    Provider Service - Provider Discovery and Instance Management
    ============================================================================

    This service provides two main capabilities:

    1. Provider Capabilities (static catalog):
    - ListProviders / GetProvider: Query the provider type catalog
    - ProviderInfo describes what each provider TYPE can do (algorithms, properties)
    - Data comes from JSON files shipped with the service

    2. Provider Instances (runtime configuration):
    - RegisterProviderInstance / UpdateProviderInstance / DeleteProviderInstance
    - ProviderInstance represents a CONFIGURED, READY-TO-USE provider
    - Multiple instances can exist per provider type (e.g., different HSM slots)
    - Instances are stored in Vault/storage, not in files

    Example workflow:
    1. Admin queries ListProviders to see available provider types
    2. Admin registers instance: { provider_id: "pkcs11", instance_id: "hsm-payments", config: {...} }
    3. User creates key: { provider_requirements: { fips_140_certified: true } }
    4. System matches requirements to instances, selects "hsm-payments"


    ========================================
    Provider Capabilities (static catalog)
    ========================================
    """

    def ListProviders(self, request, context):
        """List available provider types and their capabilities.
        Returns ProviderInfo entries from the provider catalog.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProvider(self, request, context):
        """Get details about a specific provider type.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterProviderInstance(self, request, context):
        """========================================
        Provider Instances (runtime configuration)
        ========================================

        Register a new provider instance with configuration.
        The instance's provider_id must reference a valid ProviderInfo.
        Configuration is validated against the provider's configuration_schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviderInstances(self, request, context):
        """List registered provider instances.
        Can filter by provider type, requirements, or enabled status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderInstance(self, request, context):
        """Get a specific provider instance by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProviderInstance(self, request, context):
        """Update a provider instance's configuration or properties.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProviderInstance(self, request, context):
        """Delete a provider instance.
        Fails if keys still reference this instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MatchProviders(self, request, context):
        """========================================
        Provider Matching
        ========================================

        Find provider instances matching specific requirements.
        Returns instances sorted by match score (best matches first).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviders,
                    request_deserializer=services_dot_provider__service__pb2.ListProvidersRequest.FromString,
                    response_serializer=services_dot_provider__service__pb2.ListProvidersResponse.SerializeToString,
            ),
            'GetProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProvider,
                    request_deserializer=services_dot_provider__service__pb2.GetProviderRequest.FromString,
                    response_serializer=services_dot_provider__service__pb2.GetProviderResponse.SerializeToString,
            ),
            'RegisterProviderInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterProviderInstance,
                    request_deserializer=services_dot_provider__service__pb2.RegisterProviderInstanceRequest.FromString,
                    response_serializer=services_dot_provider__service__pb2.RegisterProviderInstanceResponse.SerializeToString,
            ),
            'ListProviderInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviderInstances,
                    request_deserializer=services_dot_provider__service__pb2.ListProviderInstancesRequest.FromString,
                    response_serializer=services_dot_provider__service__pb2.ListProviderInstancesResponse.SerializeToString,
            ),
            'GetProviderInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderInstance,
                    request_deserializer=services_dot_provider__service__pb2.GetProviderInstanceRequest.FromString,
                    response_serializer=services_dot_provider__service__pb2.GetProviderInstanceResponse.SerializeToString,
            ),
            'UpdateProviderInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProviderInstance,
                    request_deserializer=services_dot_provider__service__pb2.UpdateProviderInstanceRequest.FromString,
                    response_serializer=services_dot_provider__service__pb2.UpdateProviderInstanceResponse.SerializeToString,
            ),
            'DeleteProviderInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProviderInstance,
                    request_deserializer=services_dot_provider__service__pb2.DeleteProviderInstanceRequest.FromString,
                    response_serializer=services_dot_provider__service__pb2.DeleteProviderInstanceResponse.SerializeToString,
            ),
            'MatchProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchProviders,
                    request_deserializer=services_dot_provider__service__pb2.MatchProvidersRequest.FromString,
                    response_serializer=services_dot_provider__service__pb2.MatchProvidersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'caas.crypto.v1.ProviderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('caas.crypto.v1.ProviderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProviderService:
    """============================================================================
    Provider Service - Provider Discovery and Instance Management
    ============================================================================

    This service provides two main capabilities:

    1. Provider Capabilities (static catalog):
    - ListProviders / GetProvider: Query the provider type catalog
    - ProviderInfo describes what each provider TYPE can do (algorithms, properties)
    - Data comes from JSON files shipped with the service

    2. Provider Instances (runtime configuration):
    - RegisterProviderInstance / UpdateProviderInstance / DeleteProviderInstance
    - ProviderInstance represents a CONFIGURED, READY-TO-USE provider
    - Multiple instances can exist per provider type (e.g., different HSM slots)
    - Instances are stored in Vault/storage, not in files

    Example workflow:
    1. Admin queries ListProviders to see available provider types
    2. Admin registers instance: { provider_id: "pkcs11", instance_id: "hsm-payments", config: {...} }
    3. User creates key: { provider_requirements: { fips_140_certified: true } }
    4. System matches requirements to instances, selects "hsm-payments"


    ========================================
    Provider Capabilities (static catalog)
    ========================================
    """

    @staticmethod
    def ListProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.ProviderService/ListProviders',
            services_dot_provider__service__pb2.ListProvidersRequest.SerializeToString,
            services_dot_provider__service__pb2.ListProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.ProviderService/GetProvider',
            services_dot_provider__service__pb2.GetProviderRequest.SerializeToString,
            services_dot_provider__service__pb2.GetProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterProviderInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.ProviderService/RegisterProviderInstance',
            services_dot_provider__service__pb2.RegisterProviderInstanceRequest.SerializeToString,
            services_dot_provider__service__pb2.RegisterProviderInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviderInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.ProviderService/ListProviderInstances',
            services_dot_provider__service__pb2.ListProviderInstancesRequest.SerializeToString,
            services_dot_provider__service__pb2.ListProviderInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviderInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.ProviderService/GetProviderInstance',
            services_dot_provider__service__pb2.GetProviderInstanceRequest.SerializeToString,
            services_dot_provider__service__pb2.GetProviderInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProviderInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.ProviderService/UpdateProviderInstance',
            services_dot_provider__service__pb2.UpdateProviderInstanceRequest.SerializeToString,
            services_dot_provider__service__pb2.UpdateProviderInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProviderInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.ProviderService/DeleteProviderInstance',
            services_dot_provider__service__pb2.DeleteProviderInstanceRequest.SerializeToString,
            services_dot_provider__service__pb2.DeleteProviderInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MatchProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/caas.crypto.v1.ProviderService/MatchProviders',
            services_dot_provider__service__pb2.MatchProvidersRequest.SerializeToString,
            services_dot_provider__service__pb2.MatchProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
